### ISSUE TITLE
Hay que mudar los estilos del archivo armatusangucheto.jsp a un archivo css. Como corresponde.

### ISSUE THREAD

**Issue by gerAlvarez** [gerAlvarez/UNLaM-TallerWebI-Sanguchetto#19]
Es una negrada tener los estilos en el head del jsp, hay que pasarlos a un archivo css independiente y linkear el jsp con ese archivo.

**Comment by ManuelTorresBaquedano** [comment]
Se llevo a cabo la desnegrada de tener los estilos en el head del jsp
