### ISSUE TITLE
Hay que homogeneizar la estetica de las vistas. El modelo a seguir es el de la vista armatusangucheto.

### ISSUE THREAD

**Issue by gerAlvarez** [gerAlvarez/UNLaM-TallerWebI-Sanguchetto#22]
Todas las vistas deben verse igual o similar.
El modelo a seguir es el de la vista [armatusangucheto](https://github.com/gerAlvarez/UNLaM-TallerWebI-Sanguchetto/blob/master/src/main/webapp/WEB-INF/jsp/armatusangucheto.jsp).

**Comment by ManuelTorresBaquedano** [comment]
Se homogenizan las vistas
