### ISSUE TITLE
Confirmar la compra de Sangucheto

### ISSUE THREAD

**Issue by ManuelTorresBaquedano** [gerAlvarez/UNLaM-TallerWebI-Sanguchetto#25]
Se vuelve a la solapa "Arma tu sangucheto" con los precios y productos previos al hacer clic en "Compra Sangucheto". Es decir, nunca queda descontado definitivamente el producto.

**Comment by gerAlvarez** [comment]
Se corrigió este issue en el commit d2be7b407095cbc3b046660128ed691f0cda5065
